* Recommended Books (Non Technical)
**  deep work

**  eric ries book

**  4 steps to epiphany
** Start Small Stay Small
  
**  The Millionaire Fastlane: Crack the Code to Wealth and Live Rich for a Lifetime
  
**  how to make money by P T Barnum
  http://www.fourmilab.ch/etexts/www/barnum/moneygetting/moneygetting.html
**  
**  The way of the superior man
  
**  Pressfield's "The War of Art."
  
**  The E-Myth Revisted by Michael E. Gerber is a great book about setting
  up your business structure and process and avoiding the “technician”
  trap. It’s an eye-opening read and highly recommended if you’re
  looking to start a new business.
  
**  The Personal MBA by Josh Kaufman is worth a read as well. It’s easily
  digestible and is chocked full of fundamental lessons on business.
  This is a good one to read through and then continue picking up every
  couple of months to review.
  
**  Seeking Wisdom: From Darwin to Munger is a book about human behavior.
  This is an excellent book that helps you identify pitfalls in your own
  thinking and logic. I’m about halfway through as of writing this and
  it’s significantly changed how I think about my work and my life.

**  Start Small Stay Small
  
**  Innovators Dilemma - recommended by box founder
  
**  The inner game of tennis

**  Leil Lowndes - how to talk to anyone

**  The cathedral and the bazaar
