* A. R. Harish (arh[AT]iitk.ac.in) 
PhD (IIT Kanpur) 
Phone: 0512-259-7569 (O)
Research Interests: Antennas, Radio Frequency Identification (RFID), Computational Electromagnetics.

 


* Abhay Karandikar ( ) 
PhD ( )
Phone: 
Research Interests:

 


* Abheejeet Mohapatra (abheem[AT]iitk.ac.in)
Phone: 0512-259-7152 (O)
Research Interests: Power system security, Uncertainty modelling, Stochastic analysis and optimization, Robust and efficient system operation and planning, Renewable integration in power systems, Deregulation

 


* Abhishek Kumar Gupta (gkrabhi[AT]iitk.ac.in)
Phone: 0512-259-2001 (O)
Research Interests: wireless communication, stochastic geometry and numerical methods

 


* Aditya K. Jagannatham (adityaj[AT]iitk.ac.in) 
PhD (UC San Diego) 
Phone: 0512-259-7494 (O)
Research Interests: Wireless Systems and Networks, MIMO, LTE/OFDM, UMTS/CDMA, Wireless Sensor and Ad hoc networks, Digital and Statistical Signal Processing for wireless PHY layer, Wireless Channel Estimation, Equalization and Precoding, Digital Image/Video Coding and Processing, H.264, Scalable Video Coding.

 


* Adrish Banerjee (adrish[AT]iitk.ac.in) 
PhD (Notre Dame, USA)
Phone: 0512-259-7991 (O)
Research Interests: Cognitive radio, Error control coding, Wireless communications, Optical communications.

 


* Ajit Kumar Chaturvedi (akc[AT]iitk.ac.in)
PhD (IIT Kanpur) 
Phone: 0512-259-7613 (O)
Research Interests: Communications theory and Systems, Mobile communications, Spread spectrum systems.

 


* Aloke Dutta (aloke[AT]iitk.ac.in) 
PhD (University,Baton Rouge, Louisiana) 
Phone: 0512-259-7661 (O) / 512-259-8452 (R)
Research Interests: Semiconductor device physics and modeling, Analog/Digital VLSI circuits, IC fabrication technology and device characterization, Mixed Signal RF Circuits.

 


* Amit Verma (amitkver[AT]iitk.ac.in) 
PhD (University of Notre Dame, USA) 
Phone: 0512-259-6432 (O)
Research Interests: Epitaxial growth and characterization of semiconductor thin films, Semiconductor Device Design and Fabrication, Electron Transport measurements and modeling.

 


* Ankush Sharma (ansharma[AT]iitk.ac.in) 
PhD ( )
Phone: +91-512-2592012 
Research Interests: Power Systems, Smart Grid Technology, State Estimation, IT Application into Power Systems, Smart City, Multi-Agent Systems, Wide Area Monitoring & Control of Power System, Energy Market, Demand Response Management.

 


* Animesh Biswas (abiswas[AT]iitk.ac.in) 
PhD (IIT Delhi)
Phone: 0512-259-7137 (O)
Research Interests: Electromagnetics, Micro & Millimeter wave circuits and techniques, Optical Guide structure MMICs.

 


* Baquer Mazhari (baquer[AT]iitk.ac.in) 
PhD (University of Illinois at Urbana Champaign) 
Phone: 0512-259-7924 (O) / 0512-259-8528 (R)
Research Interests: Organic Electronics.

 


* Gannavarpu Rajshekhar (gshekhar[AT]iitk.ac.in) 
PhD (Swiss Federal Institute of Technology Lausanne (EPFL)) 
Phone: 0512-259-6477 (O)
Research Interests: Quantitative Phase Imaging, Biophotonics, Optical Metrology, Applied Signal Processing, Fringe Analysis, Non-invasive Precision Metrology.

 


* Govind Sharma (govind[AT]iitk.ac.in) 
PhD (University of Southern California, Los Angeles) 
Phone: 0512-259-7922 (O)
Research Interests: Signal Processing,Communication Systems,Video signal processing,Medical image processing.

 


* K. Vasudevan (vasu[AT]iitk.ac.in) 
PhD (IIT Madras)
Phone: 0512-259-7109 (O) 
Research Interests: Digital communications, Coherent & noncoherent receivers, Synchronization, Channel estimation Diversity techniques.

 


* K. S. Venkatesh (venkats[AT]iitk.ac.in) 
PhD (IIT Kanpur)
Phone: 0512-259-7486 / 7468 / 7855 / 7846 (O)
Research Interests: Signal processing, Image and Video processing, Computer vision with applications in Robotics, Signal and System Theory.

 


* K. V. Srivastava (kvs[AT]iitk.ac.in)
PhD (IIT Kanpur)
Phone: 0512-259-7105 (O)
Research Interests: Meta-Materials, Microwave Antennas, Dielectric Resonator and its applications, Microwave Filters, Finite-Difference Time-Domain (FD-TD) Technique, Wireless Power Transfer, Electromagnetics

 


* Ketan Rajawat (ketan[AT]iitk.ac.in) 
PhD (University of Minnesota)
Phone: 0512-259-7337 (O)
Research Interests: Optimization algorithms in communications, Dynamic network measurement and cartography, Network Localization, Network Optimization.

 


* Laxmidhar Behera (lbehera[AT]iitk.ac.in)
PhD (IIT Delhi)
Phone: 0512-259-7198 (O)
Research Interests: Intelligent Systems and Control, Cognitive Robotics, Nano-robotics, Vision based Control, Soft Computing, Information Retrieval in music and language, Semantic Information Processing, Physics of Complex Systems, Cyber Physical Systems, Formation Control of UAVs, Brain-Computer Interface (BCI), Sanskrit Computational Linguistics.

 


* Mohammad Jaleel Akhtar (mjakhtar[AT]iitk.ac.in) 
PhD (University of Magdeburg, Germany) 
Phone: 0512-259-6523 (O)
Research Interests: Microwave Imaging, Characterization and Nondestructive Testing, RF and Microwave Sensors; Artificial Dielectrics and Metamaterials, Design and Testing of Advanced Composites and Metamaterials for Stealth Applications, Microwave Material Processing, Microwave Filters, Electromagnetic modeling of Metal Powder Compacts, Multi-physics Simulation and Modeling, Electromagnetic Wave Interaction with Biological Tissues, UWB Antennas.

 


* Nandini Gupta (ngupta[AT]iitk.ac.in) 
PhD (IISc Bangalore)
Phone: 0512-259- 7511 (O)
Research Interests: High Voltage Engineering, dielectric and Insulation, Plasma and gas discharges, Field estimation.

 


* Naren Naik (nnaik[AT]iitk.ac.in) 
PhD (IISc Bangalore) 
Phone: 0512-259-6518 (O)
Research Interests: Development and analysis of reconstruction algorithms for nonlinear tomography, Shape-based and dynamic tomography, Tracking and battlefield surveillance, Numerical solutions to partial differential equations in electromagnetics, Subsurface imaging with GPR, fluorescence optics, electrical impedance and photoacoustic tomography.

 


* Nishchal K. Verma (nishchal[AT]iitk.ac.in)
PhD (IIT Delhi)
Phone: 0512-[259- / 392 / 679]-6524 (O)
Research Interests: Intelligent Data mining Algorithms and applications, Health Monitoring and Intelligent Fault Diagnosis Systems, Soft-Computing in Modelling and Control, Machine Learning Algorithms, Computer Vision, Bioinformatics, Smart Grid, Intelligent Agents and their Applications, Intelligent Informatics, Fuzzy Controllers, Image frame generation, Brain Computer/ Machine Interface, Unmanned Aerial Vehicles.

 


* Parthasarathi Sensarma (sensarma[AT]iitk.ac.in) 
PhD (IISc Bangalore) 
Phone: 0512-259-7076 (O)
Research Interests: Power Electronic Applications to Power Systems,Power Quality,FACTS devices,Power Supplies, Utility Interfaces for Renewable Generation.

 


* Pradeep Kumar (pradeepk[AT]iitk.ac.in) 
PhD (IIT Madras) 
Phone: 0512-259-7570 (O) 
Research Interests: Quantum key distribution, Optical fiber communication systems, Nonlinear fiber optics.

 


* Pradip Sircar (sircar[AT]iitk.ac.in) 
PhD (Syracuse University)
Phone: 0512-259-7063 (O) / 0512-259-8213 (R)
Research Interests: Signal processing and systems, Communication theory, Computational methods.

 


* R. K. Bansal (rkb[AT]iitk.ac.in) 
PhD (University of Connecticut, Storrs) 
Phone: 0512-259-7075 (O) / 0512-259-8675 (R)
Research Interests: Universal data compression with applications, Sequential detection of a change in distribution, robust detection, Ergodic theory and large deviation theory-applications, Stochastic processes.

 


* Rajesh M. Hegde (rhegde[AT]iitk.ac.in) 
PhD (IIT Madras)
Phone: 0512-259-6248 (O)
Research Interests: Speech Signal Procesing and Recognition (with emphasis on Indian Languages), Speaker and Language Identification, Affective Speech Processing ,Multi modal signal processing ,Pervasive and Ubiquitous Computing,Applied Signal Processing in wireless networks ,IT in Emergency Response.

 


* Ramprasad Potluri (potluri[AT]iitk.ac.in) 
PhD (University of Kentucky, USA)
Phone: 0512-259-6093 (O) / 0512-259-8837 (R)
Research Interests: Practical applications of Control Systems theory.

 


* Rohit Budhiraja (rohitbr[AT]iitk.ac.in) 
PhD (IIT Madras)
Phone: 0512-259-6927 (O)
Research Interests:My research interests include:
1) Application of linear algebra, optimization methods and information theory to study problems in:
a) Cooperative wireless communications, multiuser MIMO communication systems.
b) Multi-hop and multi-cell wireless networks.

 


* S. C. Srivastava (scs[AT]iitk.ac.in) 
PhD (IIT Delhi) 
Phone: 0512-259-7625 (O) / 0512-259-8257 (R)
Research Interests: Power system dynamics & voltage stability studies,Wide Area Monitoring & Control of Power System,Optimal power dispatch and state estimation,Security analysis and control,Energy management system and distribution automation,Power system restructuring.

 


* Sandeep Anand (asandeep[AT]iitk.ac.in) 
PhD (IIT Bombay)
Phone: 0512-259-7131 (O)
Research Interests: Renewable sources based DC microgrid and power electronic converters for solar PV systems.

 


* Santanu Mishra (santanum[AT]iitk.ac.in) 
PhD (University of Florida, Gainesville)
Phone: 0512-259-6249 (O)
Research Interests: Multiphase DC/DC Power Conversion,Power Management Circuits,Modeling and Control of Power Electronics Systems.

 


* Saikat Chakrabarti (saikatc[AT]iitk.ac.in) 
PhD (Memorial University of Newfoundland,Canada)
Phone: 0512-259-6598 (O)
Research Interests: Power system dynamics and stability, Application of synchronized measurement technology to power systems, Power system state estimation,Power system reliability.

 


* Shafi Qureshi (qureshi[AT]iitk.ac.in) 
PhD (University of California)
Phone: 0512-259-7133 (O)
Research Interests: Thin Film Transistors,Device Physics and Modeling,VLSI Design, MEMS,Nuclear Radiation Detectors and Electronics.

 


* Shilpi Gupta (shilpig[AT]iitk.ac.in) 
PhD (University of Maryland College Park)
Phone: 0512-679-6231 (O) 
Research Interests: Photonics, Plasmonics, Quantum optics.

 


* Shyama Prasad Das (spdas[AT]iitk.ac.in) 
PhD (IIT Kharagpur)
Phone: 0512-259-7106 (O) / 0512-259-8599 (R)
Research Interests: Power electronics,Electric Drives,Electrical machines,Microprocessor Systems & instrumentation.

 


* Soumya Ranjan Sahoo (srsahoo[AT]iitk.ac.in) 
PhD (IIT Bombay)
Phone: 0512-259-6202 (O)
Research Interests: Nonlinear dynamical systems, Control of Unmanned aerial vehicles, Coordinated control of autonomous vehicles.

 


* Sri Niwas Singh (snsingh[AT]iitk.ac.in) 
PhD (IIT Kanpur)
Phone: 0512-259-7009 (O) / 0512-259-8509 (R)
Research Interests: Power System Restructuring,FACTS Technology,Optimal Power Dispatch and Security Analysis,Power System Dynamics, Operation and Control,Distribution System Planning and Demand Side Management,Application of Genetic Algorithms and Artificial Neural Networks in Power Systems.

 


* S. Sundar Kumar Iyer (sskiyer[AT]iitk.ac.in) 
PhD (University of California, USA)
Phone: 0512-259-7820 (O)
Research Interests: Organic solar cells , Photovoltaic systems ,Printable electronics,VLSI technology, devices and circuits.

 


* Utpal Das (utpal[AT]iitk.ac.in) 
PhD (University of Michigan) 
Phone: 0512-259-7150 / 7409 (O) / 0512-259-8628 (R)
Research Interests: Opto electronics,Semiconductor device & Lasers,Millimetric & Microwave circuits.

 


* Y. N. Singh (ynsingh[AT]iitk.ac.in) 
PhD (IIT Delhi)
Phone: 0512-[679 / 392 / 259-]-7944 (O) 
Research Interests: Telecom Networks, Telecom Switching Systems, Optical Networks and switching systems, Peer‐to‐peer networking, Complex networks, Wireless sensor networks, overlaid multicast systems.

 


* Yogesh Singh Chauhan (chauhan[AT]iitk.ac.in)
PhD (Ecole Polytechnique Federale de Lausanne (EPFL), Switzerland)
Phone: 0512-259-7244 (O) / 0512-259-7257 (Assistant)
Research Interests: Nanoelectronics Compact modeling of semiconductor devices (Bulk/SOI MOSFET, Multigate FET, Nanowire, UTBSOI and novel devices) SPICE Modelling of High Voltage/Power Semiconductor Devices (LDMOS, VDMOS, IGBT, HEMT etc.) BSIM model development and support (with BSIM Group at University of California Berkeley) Atommistic Simulation of Nanoscale Devices
DC, CV and RF Characterization.
